In [ ]:
# https://docs.google.com/spreadsheets/d/1rxv83xDAM8l9qdANiud0DyiBnYLeCdIPYfZ0SSFD6ko/edit?gid=1105617973#gid=1105617973

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
import gspread
import pandas as pd
from google.auth import default

creds, _ = default()
gc = gspread.authorize(creds)

In [13]:
!ls /content/drive/MyDrive/from_mteb_to_mtob - грамматики.csv

ls: cannot access '/content/drive/MyDrive/from_mteb_to_mtob': No such file or directory
ls: cannot access '-': No such file or directory
ls: cannot access 'грамматики.csv': No such file or directory

In [4]:
import pandas as pd

df = pd.read_csv(r"/content/drive/MyDrive/from_mteb_to_mtob - грамматики.csv", header=None)

In [5]:
df.head()

,0,1,2,3,4,5,6
0,The Takelma Language of Southwestern Oregon,Takelma,Takelma,North America,"Sapir, Edward",1909,304
1,Alsea Grammar,Oregon Coast,Alsea,North America,"Frachtenberg, Leo Joachim",1918,431
2,A Grammar of the Wappo Language,Wappo-Yukian,Wappo,North America,"Radin, Paul",1929,202
3,A grammar of the Nyimang language (Nuba Mounta...,Eastern Sudanic,Nyimang,Africa,"Stevenson, Roland C.",1938,195
4,Tunica,Tunica,Tunica,North America,"Haas, Mary R.",1941,143

In [6]:
# Define your new column names here
new_column_names = [
    "Title",
    "Language_Family",
    "Language",
    "Continent",
    "Author",
    "Year",
    "Pages"
] # Example names, please adjust as needed

# Assign new column names to the DataFrame
df.columns = new_column_names

# Display the DataFrame with new headers
df.head()

,Title,Language_Family,Language,Continent,Author,Year,Pages
0,The Takelma Language of Southwestern Oregon,Takelma,Takelma,North America,"Sapir, Edward",1909,304
1,Alsea Grammar,Oregon Coast,Alsea,North America,"Frachtenberg, Leo Joachim",1918,431
2,A Grammar of the Wappo Language,Wappo-Yukian,Wappo,North America,"Radin, Paul",1929,202
3,A grammar of the Nyimang language (Nuba Mounta...,Eastern Sudanic,Nyimang,Africa,"Stevenson, Roland C.",1938,195
4,Tunica,Tunica,Tunica,North America,"Haas, Mary R.",1941,143

In [17]:
# add ISO codes

#from glottolog https://github.com/glottolog/glottolog

!git clone https://github.com/glottolog/glottolog

Cloning into 'glottolog'...
remote: Enumerating objects: 961727, done.
remote: Counting objects: 100% (725/725), done.
remote: Compressing objects: 100% (642/642), done.
remote: Total 961727 (delta 144), reused 154 (delta 64), pack-reused 961002 (from 2)
Receiving objects: 100% (961727/961727), 1.38 GiB | 21.13 MiB/s, done.
Resolving deltas: 100% (366248/366248), done.
Updating files: 100% (27268/27268), done.

In [7]:
glotto = pd.read_csv(r"/content/drive/MyDrive/languoid.csv")

glotto.head()

,id,family_id,parent_id,name,bookkeeping,level,latitude,longitude,iso639P3code,description,markup_description,child_family_count,child_language_count,child_dialect_count,country_ids
0,3adt1234,afro1255,nort3292,3Ad-Tekles,False,dialect,NaN,NaN,NaN,NaN,NaN,0,0,0,NaN
1,aala1237,aust1307,ramo1244,Aalawa,False,dialect,NaN,NaN,NaN,NaN,NaN,0,0,0,NaN
2,aant1238,nucl1709,nort2920,Aantantara,False,dialect,NaN,NaN,NaN,NaN,NaN,0,0,0,NaN
3,aari1238,sout2845,ahkk1235,Aari-Gayil,False,family,NaN,NaN,aiz,NaN,NaN,0,2,0,NaN
4,aari1239,sout2845,aari1238,Aari,False,language,5.95034,36.5721,aiw,NaN,NaN,0,0,0,ET

In [8]:
len(glotto)

27034

In [9]:
glottolog = {}
for i in range(len(glotto)):
  glottolog[glotto.iloc[i]["name"].lower()] = glotto.iloc[i]["iso639P3code"]

In [10]:
isos = []
for i in range(len(df)):
  if df.iloc[i]['Language'].lower() in glottolog:
    isos.append(glottolog[df.iloc[i]['Language'].lower()])
  else:
    isos.append('no exact match')

In [11]:
df['iso639P3code'] = isos

In [30]:
df.to_csv(
    "/content/drive/MyDrive/updated_mtob.csv"
)

## Datasets

## SMOL

221 low resource languages -- MT to English

https://huggingface.co/datasets/google/smol

In [12]:
smol = pd.read_csv(r"/content/drive/MyDrive/smol_langs.csv")

smol.head()

,LP,Target Language Name,ISO639-3,ISO 15924 Script,Glottocode,Continent,Endonym,Alternate names,N Smoldoc,N SmolSent,N Gatitos
0,am_ar,Arabic,ara,Arab,stan1269,Asia,اللُّغَة العَرَبِيّة,Arabic (MSA); Arabic (Standard); Arabic (Fusha...,329,0,0
1,am_zh,Mandarin Chinese,zho,Hans,mand1415,Asia,汉语,NaN,329,0,0
2,en_aa,Afar,aar,Latn,afar1241,Africa,Qafar,NaN,66,863,3990
3,en_ab,Abkhaz,abk,Cyrl,abkh1244,Asia,Аҧсуа,Abkhazian,0,0,3976
4,en_ace,Acehnese,ace,Latn,aceh1245,Asia,Aceh,Achinese; Dayan; Aceh,0,0,4001

In [13]:
smol_iso = {}
for i in range(len(smol)):
  smol_iso[smol.iloc[i]["ISO639-3"]] = smol.iloc[i]["LP"]

In [14]:
isos = []
for i in range(len(df)):
  if df.iloc[i]['iso639P3code'] in smol_iso:
    isos.append(smol_iso[df.iloc[i]['iso639P3code']])
  else:
    isos.append('')

In [15]:
df['smol'] = isos

In [43]:
df.to_csv(
    "/content/drive/MyDrive/updated_mtob.csv"
)

In [19]:
df[df['smol']!='']

,Title,Language_Family,Language,Continent,Author,Year,Pages,iso639P3code,smol
139,Chamorro grammar,Austronesian,Chamorro,Papunesia,"Chung, Sandra",2020,754,cha,en_ch

## OLDI Seed

44 languages

https://huggingface.co/datasets/openlanguagedata/oldi_seed

In [17]:
oldi = pd.read_csv(r"/content/drive/MyDrive/oldi_seed.csv")

oldi.head()

  Code Script Glottocode                     Name Notes
0  ace   Arab   achi1257   Acehnese (Jawi script)   NaN
1  ace   Latn   achi1257  Acehnese (Latin script)   NaN
2  ary   Arab   moro1292          Moroccan Arabic   NaN
3  arz   Arab   egyp1253          Egyptian Arabic   NaN
4  bam   Latn   bamb1269                  Bambara   NaN

In [22]:
oldi_iso = {}
for i in range(len(oldi)):
  oldi_iso[oldi.iloc[i]["Code"]] = oldi.iloc[i]["Glottocode"]

In [23]:
isos = []
for i in range(len(df)):
  if df.iloc[i]['iso639P3code'] in oldi_iso:
    isos.append(oldi_iso[df.iloc[i]['iso639P3code']])
  else:
    isos.append('')

In [24]:
df['oldi'] = isos

In [26]:
df[df['oldi']!='']

Empty DataFrame
Columns: [Title, Language_Family, Language, Continent, Author, Year, Pages, iso639P3code, smol, oldi]
Index: []

## Flores plus

 translations primarily from English into over 200 language varieties.

https://huggingface.co/datasets/openlanguagedata/flores_plus

In [27]:
flores = pd.read_csv(r"/content/drive/MyDrive/flores_plus.csv")

flores.head()

  Code Script Glottocode                     Name Notes
0  ace   Arab   achi1257   Acehnese (Jawi script)   NaN
1  ace   Latn   achi1257  Acehnese (Latin script)   NaN
2  acm   Arab   meso1252      Mesopotamian Arabic   NaN
3  acq   Arab   taiz1242     Taʽizzi-Adeni Arabic   NaN
4  aeb   Arab   tuni1259          Tunisian Arabic   NaN

In [28]:
flores_iso = {}
for i in range(len(flores)):
  flores_iso[flores.iloc[i]["Code"]] = flores.iloc[i]["Glottocode"]

In [29]:
isos = []
for i in range(len(df)):
  if df.iloc[i]['iso639P3code'] in flores_iso:
    isos.append(flores_iso[df.iloc[i]['iso639P3code']])
  else:
    isos.append('')

In [30]:
df['flores'] = isos

In [31]:
df[df['flores']!='']

,Title,Language_Family,Language,Continent,Author,Year,Pages,iso639P3code,smol,oldi,flores
32,A Reference Grammar of Korean: A Complete Guid...,Korean,Korean,Eurasia,"Martin, Samuel E.",1992,1042,kor,,,kore1280
64,A Grammar of Basque,Basque,Basque,Eurasia,"Hualde, José I. and de Urbina, Jon Ortiz",2003,976,eus,,,basq1248

## Tatoeba

https://huggingface.co/datasets/Helsinki-NLP/tatoeba

In [33]:
iso = ["ab", "acm", "ady", "af", "afb", "afh", "aii", "ain", "ajp", "akl", "aln", "am", "an", "ang", "aoz", "apc", "ar", "arq", "ary", "arz", "as", "ast", "avk", "awa", "ayl", "az", "ba", "bal", "bar", "be", "ber", "bg", "bho", "bjn", "bm", "bn", "bo", "br", "brx", "bs", "bua", "bvy", "bzt", "ca", "cay", "cbk", "ce", "ceb", "ch", "chg", "chn", "cho", "chr", "cjy", "ckb", "ckt", "cmn", "co", "code", "cpi", "crh", "crk", "cs", "csb", "cv", "cy", "da", "de", "dng", "drt", "dsb", "dtp", "dv", "dws", "ee", "egl", "el", "emx", "en", "enm", "eo", "es", "et", "eu", "ext", "fi", "fj", "fkv", "fo", "fr", "frm", "fro", "frr", "fuc", "fur", "fuv", "fy", "ga", "gag", "gan", "gbm", "gcf", "gd", "gil", "gl", "gn", "gom", "gos", "got", "grc", "gsw", "gu", "gv", "ha", "hak", "haw", "hbo", "he", "hi", "hif", "hil", "hnj", "hoc", "hr", "hrx", "hsb", "hsn", "ht", "hu", "hy", "ia", "iba", "id", "ie", "ig", "ii", "ike", "ilo", "io", "is", "it", "izh", "ja", "jam", "jbo", "jdt", "jpa", "jv", "ka", "kaa", "kab", "kam", "kek", "kha", "kjh", "kk", "kl", "km", "kmr", "kn", "ko", "koi", "kpv", "krc", "krl", "ksh", "ku", "kum", "kw", "kxi", "ky", "dtp", "la", "laa", "lad", "lb", "ldn", "lfn", "lg", "lij", "liv", "lkt", "lld", "lmo", "ln", "lo", "lt", "ltg", "lut", "lv", "lzh", "lzz", "mad", "mai", "max", "mdf", "mfe", "mg", "mgm", "mh", "mhr", "mi", "mic", "min", "mk", "ml", "mn", "mni", "mnw", "moh", "mr", "mt", "mvv", "mwl", "mww", "my", "myv", "na", "nah", "nan", "nb", "nch", "nds", "ngt", "ngu", "niu", "nl", "nlv", "nn", "nog", "non", "nov", "npi", "nst", "nus", "nv", "ny", "nys", "oar", "oc", "ofs", "ood", "or", "orv", "os", "osp", "ota", "otk", "pa", "pag", "pal", "pam", "pap", "pau", "pcd", "pdc", "pes", "phn", "pi", "pl", "pms", "pnb", "ppl", "prg", "ps", "pt", "qu", "quc", "qya", "rap", "rif", "rm", "rn", "ro", "rom", "ru", "rue", "rw", "sa", "sah", "sc", "scn", "sco", "sd", "sdh", "se", "sg", "sgs", "shs", "shy", "si", "sjn", "sl", "sm", "sma", "sn", "so", "sq", "sr", "stq", "su", "sux", "sv", "swg", "swh", "syc", "ta", "te", "tet", "tg", "th", "thv", "ti", "tig", "tk", "tl", "tlh", "tly", "tmr", "tmw", "tn", "to", "toi", "tok", "tpi", "tpw", "tr", "ts", "tt", "tts", "tvl", "ty", "tyv", "tzl", "udm", "ug", "uk", "umb", "ur", "uz", "vec", "vep", "vi", "vo", "vro", "wa", "war", "wo", "wuu", "xal", "xh", "xqa", "yi", "yo", "yue", "zlm", "zsm", "zu", "zza"]

In [34]:
isos = []
for i in range(len(df)):
  if df.iloc[i]['iso639P3code'] in iso:
    isos.append(df.iloc[i]['iso639P3code'])
  else:
    isos.append('')

In [35]:
df['tatoeba'] = isos

In [36]:
df[df['tatoeba']!='']

Empty DataFrame
Columns: [Title, Language_Family, Language, Continent, Author, Year, Pages, iso639P3code, smol, oldi, flores, tatoeba]
Index: []

## Bouquet

https://huggingface.co/datasets/facebook/bouquet

In [38]:
bouq = pd.read_csv(r"/content/drive/MyDrive/bouquet.csv")

bouq.head()

,ISO 639-3,Secondary ISO 639-3,ISO 15924,Glottocode,Language,Family,Subgroup,Class
0,aar,NaN,Latn,NaN,Afar,Afro-Asiatic,Cushitic,P1-LR
1,agr,NaN,Latn,NaN,Aguaruna,Chicham,NaN,P1-LR
2,ami,NaN,Latn,NaN,Amis,Austronesian,East Formosan,P1-LR
3,arz,arb,Arab,NaN,Egyptian Arabic + Modern Standard Arabic,Afro-Asiatic,Central Semitic,Pivot
4,arz,arb,Latn,NaN,Romanized Egyptian Arabic + Modern Standard Ar...,Afro-Asiatic,Semitic,P1-HR

In [39]:
bouq_iso = {}
for i in range(len(bouq)):
  bouq_iso[bouq.iloc[i]["ISO 639-3"]] = bouq.iloc[i]["Language"]

In [40]:
isos = []
for i in range(len(df)):
  if df.iloc[i]['iso639P3code'] in oldi_iso:
    isos.append(bouq_iso[df.iloc[i]['iso639P3code']])
  else:
    isos.append('')

In [41]:
df['bouquet'] = isos

In [42]:
df[df['bouquet']!='']

Empty DataFrame
Columns: [Title, Language_Family, Language, Continent, Author, Year, Pages, iso639P3code, smol, oldi, flores, tatoeba, bouquet]
Index: []